check process nginx with pidfile /var/run/nginx.pid
  start program = "/usr/sbin/nginx -c /etc/nginx/nginx.conf"
  stop  program = "/usr/sbin/nginx -s stop"
  if failed host localhost port 80 protocol http then restart
  if 3 restarts within 5 cycles then timeout
